 const Data = [

    {id:0, name: 'John Coper', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:18,role:'Admin',date:'2002-02-20'},
    {id:1, name: 'Cody Fisher', email:'example@gmnail.com', title:'PM', status:'ACTIVE', age:18,role:'Member',date:"2002-02-20"},
    {id:2, name: 'Esther Howard', email:'example@gmnail.com', title:'SMM', status:'OFFLINE', age:43,role:'Ower',date:"2002-02-20"},
    {id:3, name: 'John', email:'example@gmnail.com', title:'Engeener', status:'INACTIVE', age:28,role:'Ower',date:"2002-02-20"},
    {id:4, name: 'John', email:'example@gmnail.com', title:'Targetolog', status:'ACTIVE', age:19,role:'Ower',date:"2002-02-20"},
    {id:5, name: 'Kristin', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:25,role:'Admin',date:"2002-02-20"},
    {id:6, name: 'John', email:'example@gmnail.com', title:'Developer', status:'OFFLINE', age:18,role:'Ower',date:"2002-02-20"},
    {id:7, name: 'John', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:17,role:'Ower',date:"2002-02-20"},
    {id:8, name: 'John Coper', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:18,role:'Admin',date:"2002-02-20"},
    {id:9, name: 'Cody Fisher', email:'example@gmnail.com', title:'PM', status:'ACTIVE', age:18,role:'Member',date:"2002-02-20"},
    {id:10, name: 'Esther Howard', email:'example@gmnail.com', title:'SMM', status:'OFFLINE', age:43,role:'Ower',date:"2002-02-20",},   
    {id:11, name: 'John', email:'example@gmnail.com', title:'Engeener', status:'INACTIVE', age:28,role:'Ower',date:"2002-02-20"},
    // {id:12, name: 'John', email:'example@gmnail.com', title:'Targetolog', status:'ACTIVE', age:19,role:'Ower',date:"2002-02-20"},
    // {id:13, name: 'Kristin', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:25,role:'Admin',date:"2002-02-20"},
    // {id:14, name: 'John', email:'example@gmnail.com', title:'Developer', status:'OFFLINE', age:18,role:'Ower',date:"2002-02-20"},
    // {id:15, name: 'John Coper', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:18,role:'Admin',date:"2002-02-20"},
    // {id:16, name: 'Cody Fisher', email:'example@gmnail.com', title:'PM', status:'ACTIVE', age:18,role:'Member',date:"2002-02-20"},
    // {id:17, name: 'Esther Howard', email:'example@gmnail.com', title:'SMM', status:'OFFLINE', age:43,role:'Ower',date:"2002-02-20"},
    // {id:18, name: 'John', email:'example@gmnail.com', title:'Engeener', status:'INACTIVE', age:28,role:'Ower',date:"2002-02-20"},
    // {id:19, name: 'John', email:'example@gmnail.com', title:'Targetolog', status:'ACTIVE', age:19,role:'Ower',date:"2002-02-20"},
    // {id:20, name: 'Kristin', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:25,role:'Admin',date:"2002-02-20"},    
    // {id:21, name: 'John', email:'example@gmnail.com', title:'Developer', status:'OFFLINE', age:18,role:'Ower'},
    // {id:22, name: 'John Coper', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:18,role:'Admin'},
    // {id:23, name: 'Cody Fisher', email:'example@gmnail.com', title:'PM', status:'ACTIVE', age:18,role:'Member'},
    // {id:24, name: 'Esther Howard', email:'example@gmnail.com', title:'SMM', status:'OFFLINE', age:43,role:'Ower'},
    // {id:25, name: 'John', email:'example@gmnail.com', title:'Engeener', status:'INACTIVE', age:28,role:'Ower'},
    // {id:26, name: 'John', email:'example@gmnail.com', title:'Targetolog', status:'ACTIVE', age:19,role:'Ower'},
    // {id:27, name: 'Kristin', email:'example@gmnail.com', title:'Developer', status:'ACTIVE', age:25,role:'Admin'},
    // {id:28, name: 'John', email:'example@gmnail.com', title:'Developer', status:'OFFLINE', age:18,role:'Ower'},
    
];

export default Data;